server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bms?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # dubbo
  dubbo:
    application.name: management-provider
    registry.address: zookeeper://192.168.88.128:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.cc.gmp
  # log spring profile
  profiles:
    active: dev

# mybatis
mybatis:
  configLocation: classpath:/mybatis-config.xml
  mapperLocations: classpath:/com/cc/gmp/mapper/**/*DAO.xml
  typeAliasesPackage: com.cc.gmp.*.entity

# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# log
logging:
  level: debug # info, debug, error
  config: classpath:logback-spring.xml
